version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dt-binance-bot
    image: dtuncbilek/dt-binance-bot:0.0.1
    restart: unless-stopped
#    volumes:
#      - ./:/app
    # ports:
    #   - 3000:3000
    networks:
      - mariadb_network
      - nginxproxymanager_default

networks:
  mariadb_network:
    external: true
  nginxproxymanager_default:
    external: true