version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dt-raider-api
    image: dtuncbilek/dt-raider-api:0.1
    restart: unless-stopped
#    volumes:
#      - ./:/app
    ports:
       - "18751:3000"
    networks:
      - mariadb_network
      - nginxproxymanager_default

networks:
  mariadb_network:
    external: true
  nginxproxymanager_default:
    external: true